services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - Django_ileri_web_programlama/docker.env
    volumes:
      - .:/srv/app
    ports:
      - "0.0.0.0:8000:8000"  # Changed port from 8000 to 8080
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  static-data:
